cursor #1c1b20
cursor_text_color #48454e

foreground            #1c1b20
background            #fdf8ff
selection_foreground  #ffffff
selection_background  #c9c3dc
url_color             #605790

color0   #fdf8ff
color1   #883648
color2   #256c33
color3   #8b6d06
color4   #625897
color5   #e6deff
color6   #605790
color7   #272628
color8   #bcbbbf
color9   #ac5669
color10  #469d57
color11  #a88727
color12  #685da5
color13  #8c84b8
color14  #9c96bb
color15  #d4d3d8
