# [mgr]
# prepend_keymap = [
#   { on = ["M","s"], run = "plugin sshfs -- menu",            desc = "Open SSHFS options" },
# ]
[mgr]
prepend_keymap = [
  { on = ["M","s"], run = "plugin sshfs -- menu",            desc = "Open SSHFS options" },
  { on = ["M","m"], run = "plugin sshfs -- mount --jump",    desc = "Mount & jump" },
  { on = ["M","u"], run = "plugin sshfs -- unmount",         desc = "Unmount SSHFS" },
  { on = ["M","t"], run = "plugin sshfs -- terminal",        desc = "SSH Terminal" },
  { on = ["M","a"], run = "plugin sshfs -- add",             desc = "Add SSH host" },
  { on = ["M","r"], run = "plugin sshfs -- remove",          desc = "Remove SSH host" },
  { on = ["M","h"], run = "plugin sshfs -- home",            desc = "Go to mount home" },
  { on = ["M","c"], run = "cd ~/.ssh/",                      desc = "Go to ssh config" },
  { on = ["M","l"], run = "plugin sshfs -- hosts",           desc = "Open custom host list" },
  { on = "y", run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]},
  { on = "l", run = "plugin smart-enter", 					 desc = "Enter the child directory, or open the file"},
  { on = "!", for = "unix", run='shell "$SHELL" --block', 	 desc = "Open $SHELL here"},
  { on = "!", for = "windows", run='shell "pwsh" --block',  desc = "Open PowerShell here"},
]

# [[mgr.prepend_keymap]]
# on   = "!"
# for  = "unix"
# run  = 'shell "$SHELL" --block'
# desc = "Open $SHELL here"

# If you also using Yazi on Windows:
[[mgr.prepend_keymap]]
on   = "!"
for  = "windows"
run  = 'shell "pwsh" --block'
desc = "Open PowerShell here"

[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = '''
    shell --interactive --block '
        read -rp "SSH Target: " target;
        if [ -n "$target" ]; then
        	cd sftp://bo-jsk$target/usr/local/gkretail/${target^^}
        fi
    '
'''
desc = "Connect to dynamic SSH server"
