[qt]
GUIEffects=none
KDE\contrast=4
KWinPalette\activeBackground=#eaf3e9
KWinPalette\activeBlend=#e3e5e7
KWinPalette\activeForeground=#000000
KWinPalette\activeTitleBtnBg=#eaf3e9
KWinPalette\frame=#eaf3e9
KWinPalette\inactiveBackground=#eaf3e9
KWinPalette\inactiveBlend=#eff0f1
KWinPalette\inactiveForeground=#5d615d
KWinPalette\inactiveFrame=#eaf3e9
KWinPalette\inactiveTitleBtnBg=#eaf3e9
Palette\active=#1f2822, #f7fff4, #ffffff, #f4f9f4, #839182, #baceb8, #1f2822, #ffffff, #1f2822, #fafff7, #eaf3e9, #444b43, #83a572, #000000, #3a5d28, #9264a7, #f2faef, #000000, #f2faef, #1f2822, #6d8081, #83a572
Palette\disabled=#9ba49c, #cdffb6, #ffffff, #e5f0e4, #7d8a7b, #b2c5b0, #a5aba4, #ffffff, #a3aba3, #d3ffb2, #d9ead7, #444b43, #d9ead7, #9ba49c, #aebda6, #cebed4, #ddf2d5, #000000, #f2faef, #1f2822, #bfc9c4, #d9ead7
Palette\inactive=#1f2822, #f7fff4, #ffffff, #f4f9f4, #839182, #baceb8, #1f2822, #ffffff, #1f2822, #fafff7, #eaf3e9, #444b43, #c2e5b2, #1f2822, #3a5d28, #9264a7, #f2faef, #000000, #f2faef, #1f2822, #6d8081, #c2e5b2
font="Noto Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
